name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: ghcr.io/llllera/admin2
  APP_PORT: 60080
  CONTAINER_PORT: 8109
  
permissions:
  contents: read
  packages: write 
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  test:
    needs: build-and-push   # теперь тест зависит от сборки
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_DB: kubsu
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          cd .
          pip install .[test]
          pip install pytest httpx

      - name: Debug Python path
        run: |
          echo "PYTHONPATH: $PYTHONPATH"
          echo "Current directory: $(pwd)"
          ls -la

      - name: Run tests
        run: |
          cd .
          PYTHONPATH=$(pwd) pytest -v tests

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH key
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE }}
        run: |
           SSH_DIR="$RUNNER_TEMP/.ssh"
           mkdir -p "$SSH_DIR"
           echo "${{ secrets.SSH_PRIVATE }}" > "$SSH_DIR/kub_key"
           chmod 600 "$SSH_DIR/kub_key"
          
           # Для использования в следующих шагах
           echo "SSH_DIR=$SSH_DIR" >> $GITHUB_ENV
           echo "Ключ сохранён в: $SSH_DIR/kub_key"
           # Команды для выполнения на сервере
           SSH_COMMANDS=$(cat <<EOF
           echo '${{ secrets.GITHUB_TOKEN }}' | podman login ghcr.io -u '${{ github.actor }}' --password-stdin
           podman pull '${{ env.DOCKER_IMAGE }}:latest'
           podman stop app || true
           podman rm app || true
           podman run -d --name app --network=host '${{ env.DOCKER_IMAGE }}:latest'
           DATABASE_URL=postgresql+psycopg://kubsu:kubsu@localhost:5432/kubsu
           EOF
           )
          
           # Подключение с использованием сохранённого ключа
           ssh -v -i "SSH_KEY_PATH" \
              -o StrictHostKeyChecking=no \
              -p 58529 \
              tereshkova@kubsu.tyvik.ru \
              "$SSH_COMMANDS"
