name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: ghcr.io/llllera/admin2
  APP_PORT: 60080
  CONTAINER_PORT: 8109
  
permissions:
  contents: read
  packages: write 
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  test:
    needs: build-and-push   # теперь тест зависит от сборки
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_DB: kubsu
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          cd .
          pip install .[test]
          pip install pytest httpx

      - name: Debug Python path
        run: |
          echo "PYTHONPATH: $PYTHONPATH"
          echo "Current directory: $(pwd)"
          ls -la

      - name: Run tests
        run: |
          cd .
          PYTHONPATH=$(pwd) pytest -v tests

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH key
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE }}
        run: |
          mkdir -p ~/.ssh || true
          echo "$SSH_KEY" > ~/.ssh/kub_key
          chmod 600 ~/.ssh/kub_key
          ssh-keyscan -H kubsu.tyvik.ru >> ~/.ssh/known_hosts

      - name: Deploy to server
        shell: bash
        run: |
          ssh -i ~/.ssh/kub_key -p 58529 tereshkova@kubsu.tyvik.ru "
          echo '${{ secrets.GITHUB_TOKEN }}' | podman login ghcr.io -u '${{ github.actor }}' --password-stdin
          podman pull '${{ env.DOCKER_IMAGE }}:latest'
          podman stop app || true
          podman rm app || true
          podman run -d --name app -p '${{ env.APP_PORT }}:${{ env.CONTAINER_PORT }}' '${{ env.DOCKER_IMAGE }}:latest'"
    

          
          ssh -i ~/.ssh/kub_key -o StrictHostKeyChecking=no -p 58529 tereshkova@kubsu.tyvik.ru "$SSH_COMMANDS"
